"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getLastThreeQuartersStartDate = exports.hoursToMinutes = exports.dateStringToISOFormat = exports.isISOString = exports.isValidDate = void 0;
const isISOString = (isoString) => /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(isoString);
exports.isISOString = isISOString;
const isValidDate = (d) => !isNaN(d.getTime());
exports.isValidDate = isValidDate;
const dateStringToISOFormat = (dateString) => new Date(dateString).toISOString();
exports.dateStringToISOFormat = dateStringToISOFormat;
const hoursToMinutes = (hours) => hours * 60;
exports.hoursToMinutes = hoursToMinutes;
const getLastThreeQuartersStartDate = (dateString) => {
    const currentDate = dateString ? new Date(dateString) : new Date();
    const currentMonth = currentDate.getMonth();
    const currentQuarter = Math.floor(currentMonth / 3) + 1;
    currentDate.setMonth(currentQuarter * 3 - 3);
    currentDate.setDate(1);
    const previous3QuartersDate = new Date(currentDate.toISOString());
    previous3QuartersDate.setMonth(previous3QuartersDate.getMonth() - 9);
    return `${previous3QuartersDate.getFullYear()}/${previous3QuartersDate.getMonth() + 1}/${previous3QuartersDate.getDate()}`;
};
exports.getLastThreeQuartersStartDate = getLastThreeQuartersStartDate;
